# Compared to the normal environment, we made the following changes:
# Added Sphinx, myst-parser and sphinx-rtd-theme
# Removed some of the bigger packages such as pytorch, they're not needed for most of the code.
name: sphinx
channels:
  - conda-forge
dependencies:
  - matplotlib-base
  - tifffile
  - scikit-image
  - scikit-learn
  - scipy
  - nd2reader
  - pyside6
  - pandas
  - h5py
  - lifelines
  - tqdm
  - aicspylibczi
  - ome-zarr
  - geff
  - sphinx=9.1.0
  - myst-parser=5.0.0  # Markdown parsing
  - pip
  - pip:
    - sphinx-rtd-theme==3.1.0  # Nicer theme (installed via PIP; same package on Conda-forge doesn't work with Sphinx 9)
