# Compared to the normal environment, we made the following changes:
# Added Sphinx, myst-parser and sphinx-rtd-theme
# Removed some of the bigger packages such as pytorch, they're not needed for most of the code.
name: sphinx
channels:
  - conda-forge
  - defaults
dependencies:
  - matplotlib-base
  - numpy
  - pip
  - python
  - tifffile
  - scikit-image
  - scipy
  - nd2reader
  - pyside2
  - sphinx=5.0.2
  - pip:
    - myst-parser==0.18.0 # Markdown parsing
    - sphinx-rtd-theme==1.0.0 # Nicer theme
