import unittest

import numpy
import tifffile
import matplotlib.pyplot as plt
from particle_detection.gaussian_fit import Gaussian


class TestGaussianFit(unittest.TestCase):

    def test_generate_gaussian(self):
        """Basic test to see if a sensible Gaussian is generated by gaussian_fit.gaussian_3d."""
        image = numpy.zeros((15, 24, 25), dtype=numpy.uint8)  # Order: z, y, x

        max_value = 255
        gaussian = Gaussian(max=max_value, mu_x=15, mu_y=11, mu_z=7, cov_xx=10, cov_yy=10, cov_zz=4, cov_xy=6, cov_xz=0, cov_yz=0)
        gaussian.add_to_image(image)
        self.assertEquals(max_value, image[int(gaussian.mu_z), int(gaussian.mu_y), int(gaussian.mu_x)])

        # Next to the peak, the intensity must be lower (== the max must be greater than the intensity there)
        self.assertGreater(max_value, image[int(gaussian.mu_z), int(gaussian.mu_y + 1), int(gaussian.mu_x + 1)])

        tifffile.imshow(image)
        plt.show()
